### ISSUE TITLE
Can you show me some frontend Image?

### ISSUE THREAD

**Issue by searaoracle** [jahfwed/monslider#1]
I'm interested in your project. Can you show me some frontend Image?
Does it look like this slider module: https://addons.prestashop.com/en/sliders-galleries/26873-slider-pro.html

**Comment by jahfwed** [comment]
Hello,
I developed this module 5 years ago during a trainee, not even a finalized module, hence there are way more interesting gallery modules that are free and responsive ;) and with a better code inside, I swear ! :)
Thanks for your message anyway :) but feel free to use and modify it if you like.
